### ISSUE TITLE
I am not able to use any modules from the kernel.

### ISSUE THREAD

**Issue by unicorn-security-team** [kimocoder/nethunter_kernel_oneplus_nord#16]
Hi,
I am having issues with nethunter on OnePlus Nord, TWRP install is not working. I have followed all steps including format data, removing encryption etc, but it tells me to use Magisk method instead. So I tried to flash the kernel via TWRP and then install the rest using the Magisk. Everything seems ok at first glance, but kernel modules are not loaded, so no external WiFi adapter is working.

Device: Oneplus Nord
OS: OOS 11.1.5.5 EU
Running kernel: 4.19.129-kimocoder
Removed disk encryption, fully rooted, I have followed steps on the official Kali website.
TWRP: nethunter-2021.3-oneplus_nord-eleven-kalifs-full.zip won't install, tells me to use Magisk.

Thank you for help.

**Comment by Decapitater** [comment]
Till the last time , the wifi card were non functional see the issues #4  #1
The internal card does not support packet injection

**Comment by Decapitater** [comment]
@unicorn-security-team check issue #15 for the wifi shutdown bug

**Comment by Decapitater** [comment]
@kimocoder any updates ?

**Comment by Decapitater** [comment]
@unicorn-security-team are you able to use external wifi

**Comment by unicorn-security-team** [comment]
It was my fault, thinking TL-WN722N v1 is supported since it works on almost all devices. But it seems that AR9271 is not implemented yet. Ralinks work fine.

**Comment by Decapitater** [comment]
Tlwn725n ?, tlwn822n , archer T2u plus , tl wn722n ?
Is anyone working
