### ISSUE TITLE
Wifi injection not working 

### ISSUE THREAD

**Issue by Decapitater** [kimocoder/nethunter_kernel_oneplus_nord#5]
Wifi injection is not working as supposed to 
Aireplay-ng shows No Ap founds
Cannot capture Handshakes
Cannot Deauth
i tried different firmware packages including one by magisk 
Bettercap also refuses to capture as well as kismet

**Comment by Decapitater** [comment]
@kimocoder please help

**Comment by kimocoder** [comment]
WiFi injection is working fine.
Better if you could provide logs, outputs or screenshots of procedure 'cause I can't really get anything out of that less Information 👍

**Comment by Decapitater** [comment]
deauth is not working in any case any way i can provide more info

**Comment by kimocoder** [comment]
And you trying to inject packets with internal adapter?

**Comment by Decapitater** [comment]
yes i guess so

**Comment by Decapitater** [comment]
![Uploading Screenshot_20210725-111155.jpg…]()

**Comment by Decapitater** [comment]
i cannot comprehend at the moment sorry for small brain moment

**Comment by Decapitater** [comment]
oh i understand that wifi injection ie monitor mode is usable and working but packet injection is non functional
