### ISSUE TITLE
Random bugs list

### ISSUE THREAD

**Issue by Decapitater** [kimocoder/nethunter_kernel_oneplus_nord#7]
Sometimes auto rotate refuses to work at all and will only work after rebooting several times.

Strangely it's also linked with other issues that can be noticed 
Like cellular call and internet will not work 
The notification panel will show less icons and will move rest on new page 
Fingerprint sensor will refuse to work at all 
Proximity sensor is a bust, doesnt work at all 
I was about to make a issue on it but realised that it's somehow all related
Video function doesnt work  needs restart to make it work and again stop after 30 min

I was unable to make a procedure to repeat the bugs but will update as soon as I do 

EDIT: It happens randomly and everytime I need to reboot the device pls help
@kimocoder

**Comment by BG7UHS** [comment]
Can your camera record function be used normally? Mine is very lagging.

**Comment by Decapitater** [comment]
Mate turn 30 fps to 60 fps in video

**Comment by Decapitater** [comment]
@BG7UHS any success on wifi injection ?

**Comment by Decapitater** [comment]
ah sorry my bad its was because i disabled a couple of apps

**Comment by kimocoder** [comment]
New kernel release tomorrow fixes the mentioned issues + more not mentioned.
