### ISSUE TITLE
Broken Functions

### ISSUE THREAD

**Issue by Decapitater** [kimocoder/nethunter_kernel_oneplus_nord#9]
Hi
after using the kernel for some while i realised its a good kernel with many advantages the default kernel packed with nethunter image wasn't working good enough.I'm really happy after using the kernel
 
Some broken functions are:-
Proximity sensor is not working , it was working when i tried the original kernel and default kernel 
Fingerprint sensor
Auto rotate 
Pocketmode
Panorama mode is busted
videos cannot be recorded 

I really appreciate the work it took to create the kernel and how quickly it was presented as its only a few days more than a month when the source code was released. @kimocoder

**Comment by Decapitater** [comment]
ah my bad

**Comment by Decapitater** [comment]
@kimocoder  Help

**Comment by kimocoder** [comment]
New kernel coming tomorrow

**Comment by kimocoder** [comment]
Also turned off the OTG switch so USB devices are plug'n'play without that annoying 10 minutes switch-of (added in OxygenOS, System Settings).

**Comment by kimocoder** [comment]
Here is a flashable zip. flash in TWRP or FKM.

[NEWKERNEL.zip](https://github.com/kimocoder/nethunter_kernel_oneplus_nord/files/6872614/NEWKERNEL.zip)

**Comment by Decapitater** [comment]
Thanks

**Comment by Decapitater** [comment]
is it the new kernel zip ?

> Here is a flashable zip. flash in TWRP or FKM.
> 
> [NEWKERNEL.zip](https://github.com/kimocoder/nethunter_kernel_oneplus_nord/files/6872614/NEWKERNEL.zip)

**Comment by kimocoder** [comment]
Yes

**Comment by Decapitater** [comment]
@kimocoder  all works thanks
closing now !
